=== snapshot-labs/snapshot.js/src/schemas/space.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Space",
  "definitions": {
    "Space": {
      "title": "Space",
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "name",
          "minLength": 1,
          "maxLength": 32
        },
        "private": {
          "type": "boolean"
        },
        "about": {
          "type": "string",
          "title": "about",
          "maxLength": 160
        },
        "guidelines": {
          "type": "string",
          "format": "customUrl",
          "title": "guidelines",
          "maxLength": 256
        },
        "template": {
          "type": "string",
          "title": "template",
          "maxLength": 1024
        },
        "terms": {
          "type": "string",
          "title": "terms",
          "format": "customUrl",
          "maxLength": 256
        },
        "avatar": {
          "type": "string",
          "title": "avatar",
          "format": "customUrl",
          "maxLength": 256
        },
        "cover": {
          "type": "string",
          "title": "avatar",
          "format": "customUrl",
          "maxLength": 256
        },
        "location": {
          "type": "string",
          "title": "location",
          "maxLength": 24
        },
        "website": {
          "type": "string",
          "title": "website",
          "format": "customUrl",
          "maxLength": 256
        },
        "twitter": {
          "type": "string",
          "title": "twitter",
          "pattern": "^[A-Za-z0-9_]*$",
          "maxLength": 15
        },
        "coingecko": {
          "type": "string",
          "title": "coingecko",
          "pattern": "^[a-z0-9-]*$",
          "maxLength": 32
        },
        "github": {
          "type": "string",
          "title": "github",
          "pattern": "^[A-Za-z0-9_-]*$",
          "maxLength": 39
        },
        "email": {
          "type": "string",
          "title": "email",
          "maxLength": 32
        },
        "network": {
          "type": "string",
          "snapshotNetwork": true,
          "title": "network",
          "minLength": 1,
          "maxLength": 32
        },
        "symbol": {
          "type": "string",
          "title": "symbol",
          "maxLength": 16
        },
        "skin": {
          "type": "string",
          "title": "skin",
          "maxLength": 32
        },
        "domain": {
          "type": "string",
          "title": "domain",
          "maxLength": 64,
          "format": "domain"
        },
        "discussions": {
          "type": "string",
          "format": "uri",
          "title": "Discussions link",
          "maxLength": 256
        },
        "discourseCategory": {
          "type": "integer",
          "minimum": 1,
          "title": "Discourse category"
        },
        "strategies": {
          "type": "array",
          "minItems": 1,
          "uniqueItems": true,
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "maxLength": 64,
                "title": "name"
              },
              "network": {
                "type": "string",
                "maxLength": 12,
                "title": "network",
                "snapshotNetwork": true
              },
              "params": {
                "type": "object",
                "title": "params"
              }
            },
            "required": ["name"],
            "additionalProperties": false
          },
          "title": "strategies"
        },
        "members": {
          "type": "array",
          "maxItems": 100,
          "items": {
            "type": "string",
            "anyOf": [
              { "format": "evmAddress" },
              { "format": "starknetAddress" }
            ],
            "errorMessage": "Must be a valid address"
          },
          "title": "members",
          "uniqueItems": true
        },
        "admins": {
          "type": "array",
          "maxItems": 100,
          "items": {
            "type": "string",
            "anyOf": [
              { "format": "evmAddress" },
              { "format": "starknetAddress" }
            ],
            "errorMessage": "Must be a valid address"
          },
          "title": "admins",
          "uniqueItems": true
        },
        "moderators": {
          "type": "array",
          "maxItems": 100,
          "items": {
            "type": "string",
            "anyOf": [
              { "format": "evmAddress" },
              { "format": "starknetAddress" }
            ],
            "errorMessage": "Must be a valid address"
          },
          "title": "moderators",
          "uniqueItems": true
        },
        "filters": {
          "type": "object",
          "properties": {
            "defaultTab": {
              "type": "string"
            },
            "minScore": {
              "type": "number",
              "minimum": 0
            },
            "onlyMembers": {
              "type": "boolean"
            },
            "invalids": {
              "type": "array",
              "items": {
                "type": "string",
                "maxLength": 64
              },
              "title": "invalids"
            }
          },
          "additionalProperties": false
        },
        "validation": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 64,
              "title": "name"
            },
            "params": {
              "type": "object",
              "title": "params"
            }
          },
          "required": ["name"],
          "additionalProperties": false
        },
        "voteValidation": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 32,
              "title": "name"
            },
            "params": {
              "type": "object",
              "title": "params"
            }
          },
          "required": ["name"],
          "additionalProperties": false
        },
        "followValidation": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 32,
              "title": "name"
            },
            "params": {
              "type": "object",
              "title": "params"
            }
          },
          "required": ["name"],
          "additionalProperties": false
        },
        "delegationPortal": {
          "type": "object",
          "properties": {
            "delegationType": {
              "type": "string",
              "title": "Delegation type",
              "description": "Specify the type of delegation that you are using",
              "anyOf": [
                { "const": "compound-governor", "title": "Compound governor" },
                { "const": "split-delegation", "title": "Split Delegation" }
              ]
            },
            "delegationContract": {
              "type": "string",
              "title": "Contract address",
              "description": "The address of your delegation contract",
              "examples": ["0x3901D0fDe202aF1427216b79f5243f8A022d68cf"],
              "anyOf": [
                { "format": "evmAddress" },
                { "format": "starknetAddress" }
              ],
              "errorMessage": "Must be a valid EVM of Starknet address"
            },
            "delegationNetwork": {
              "type": "string",
              "title": "Delegation network",
              "description": "The network of your delegation contract",
              "anyOf": [
                { "snapshotNetwork": true },
                { "starknetNetwork": true }
              ],
              "errorMessage": "Must be a valid network"
            },
            "delegationApi": {
              "type": "string",
              "format": "uri",
              "title": "Delegation API",
              "description": "The URL of your delegation API (e.g a subgraph)",
              "examples": [
                "https://subgrapher.snapshot.org/subgraph/arbitrum/FTzC6VrZd8JhJgWfTJnwWgH1Z1dS3GxaosKkRbCqkZAZ"
              ]
            }
          },
          "required": ["delegationType", "delegationApi", "delegationContract"],
          "additionalProperties": false
        },
        "allowAlias": {
          "type": "boolean"
        },
        "plugins": {
          "type": "object"
        },
        "voting": {
          "type": "object",
          "properties": {
            "delay": {
              "type": "integer",
              "minimum": 0,
              "maximum": 2592000,
              "errorMessage": {
                "maximum": "Delay must be less than 30 days"
              }
            },
            "period": {
              "type": "integer",
              "minimum": 0,
              "maximum": 31622400,
              "errorMessage": {
                "maximum": "Delay must be less than a year"
              }
            },
            "type": {
              "type": "string",
              "title": "type"
            },
            "quorum": {
              "type": "number",
              "minimum": 0
            },
            "quorumType": {
              "type": "string",
              "enum": ["rejection"]
            },
            "blind": {
              "type": "boolean"
            },
            "hideAbstain": {
              "type": "boolean"
            },
            "aliased": {
              "type": "boolean"
            },
            "privacy": {
              "type": "string",
              "enum": ["", "shutter", "any"]
            }
          },
          "additionalProperties": false
        },
        "categories": {
          "type": "array",
          "maxItems": 2,
          "items": {
            "type": "string",
            "enum": [
              "protocol",
              "social",
              "investment",
              "grant",
              "service",
              "media",
              "creator",
              "collector",
              "ai-agent",
              "gaming",
              "wallet",
              "music",
              "layer-2",
              "defai",
              "defi",
              "rwa",
              "depin",
              "meme"
            ]
          }
        },
        "treasuries": {
          "type": "array",
          "maxItems": 10,
          "uniqueItems": true,
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "title": "Name",
                "examples": ["e.g. Balancer DAO 1"],
                "minLength": 1,
                "maxLength": 64
              },
              "address": {
                "type": "string",
                "title": "Contract address",
                "examples": ["e.g. 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984"],
                "anyOf": [
                  { "format": "evmAddress" },
                  { "format": "starknetAddress" }
                ],
                "errorMessage": "Must be a valid EVM of Starknet address"
              },
              "network": {
                "type": "string",
                "title": "Network",
                "anyOf": [
                { "snapshotNetwork": true },
                { "starknetNetwork": true }
              ],
              "errorMessage": "Must be a valid network"
              }
            },
            "required": ["name", "address", "network"],
            "additionalProperties": false
          }
        },
        "labels": {
          "type": "array",
          "maxItems": 10,
          "uniqueItems": true,
          "items":{
            "type": "object",
            "properties": {
              "id":{
                "type": "string",
                "title": "Id",
                "minLength": 1,
                "maxLength": 8
              },
              "name": {
                "type": "string",
                "title": "Name",
                "minLength": 1,
                "maxLength": 32
              },
              "description": {
                "type": "string",
                "title": "Description",
                "maxLength": 100
              },
              "color": {
                "type": "string",
                "title": "Color",
                "format": "color"
              }
            },
            "required": ["id", "name", "color"],
            "additionalProperties": false
          }
        },
        "parent": {
          "type": "string",
          "title": "parent"
        },
        "children": {
          "type": "array",
          "maxItems": 16,
          "title": "children",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        },
        "boost": {
          "type": "object",
          "properties": {
            "enabled": {
              "type": "boolean"
            },
            "bribeEnabled": {
              "type": "boolean"
            }
          },
          "required": ["enabled", "bribeEnabled"],
          "additionalProperties": false
        },
        "skinSettings": {
          "type": "object",
          "properties": {
            "bg_color": {
              "type": "string",
              "format": "color"
            },
            "link_color": {
              "type": "string",
              "format": "color"
            },
            "text_color": {
              "type": "string",
              "format": "color"
            },
            "content_color": {
              "type": "string",
              "format": "color"
            },
            "border_color" : {
              "type": "string",
              "format": "color"
            },
            "heading_color" : {
              "type": "string",
             "format": "color"
            },
            "primary_color": {
              "type": "string",
              "format": "color"
            },
            "header_color": {
              "type": "string",
              "format": "color"
            },
            "theme": {
              "type": "string",
              "enum": ["light", "dark"]
            },
            "logo": {
              "type": "string",
              "title": "logo",
              "format": "customUrl",
              "maxLength": 256
            }
          },
          "additionalProperties": false
        }
      },
      "required": ["name", "network", "strategies"],
      "additionalProperties": false
    }
  }
}

=== snapshot-labs/snapshot.js/test/examples/space.json
{
  "name": "Loot Owners",
  "skin": "indexed",
  "about": "",
  "admins": [
    "0xF296178d553C8Ec21A2fBD2c5dDa8CA9ac905A00"
  ],
  "avatar": "https://pbs.twimg.com/profile_images/1431587138202701826/lpgblc4h_400x400.jpg",
  "github": "lootproject",
  "symbol": "LOOT",
  "filters": {
    "minScore": 1,
    "onlyMembers": false
  },
  "members": [],
  "network": "1",
  "plugins": {},
  "twitter": "lootproject",
  "discussions": "https://discuss.ens.domains/",
  "discourseCategory": 28,
  "domain": "vote.lootproject.abc",
  "strategies": [
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7"
      }
    }
  ],
  "validation": {
    "name": "basic",
    "params": {}
  },
  "voting": {
    "delay": 2592000,
    "period": 15552000,
    "quorum": 100,
    "privacy": "any"
  },
  "treasuries": [
    {
      "name": "EVM treasury with checksummed address",
      "address": "0xF296178d553C8Ec21A2fBD2c5dDa8CA9ac905A00",
      "network": "1"
    },
    {
      "name": "EVM treasury with lowercase address",
      "address": "0xf296178d553c8ec21a2fbd2c5dda8ca9ac905a00",
      "network": "1"
    },
    {
      "name": "Mainnet Starknet treasury",
      "address": "0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947",
      "network": "0x534e5f4d41494e"
    }
  ],
  "labels": [
    {
        "id": "4b6a8c88",
        "name": "Test 1",
        "description": "Test Description 1",
        "color": "#48CB0D"
    },
    {
        "id": "893b2f3",
        "name": "Test 2",
        "color": "#FBE54E"
    }
  ]
}

=== snapshot-labs/snapshot.js/test/examples/space-turbo.json
{
  "name": "Loot Owners",
  "skin": "indexed",
  "about": "",
  "admins": [
    "0xF296178d553C8Ec21A2fBD2c5dDa8CA9ac905A00"
  ],
  "avatar": "https://pbs.twimg.com/profile_images/1431587138202701826/lpgblc4h_400x400.jpg",
  "github": "lootproject",
  "symbol": "LOOT",
  "filters": {
    "minScore": 1,
    "onlyMembers": false
  },
  "members": [],
  "network": "1",
  "plugins": {},
  "twitter": "lootproject",
  "strategies": [
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7"
      }
    },
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0x0e42acBD23FAee03249DAFF896b78d7e79fBD58E"
      }
    },
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
      }
    },
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0x6c3f90f043a72fa612cbac8115ee7e52bde6e490"
      }
    },
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0x1f9840a85d5af5bf1d1762f925bdaddc4201f984"
      }
    },
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9"
      }
    },
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
      }
    },
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"
      }
    },
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0xbbbbca6a901c926f240b89eacb641d8aec7aeafd"
      }
    },
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f"
      }
    }
  ],
  "validation": {
    "name": "basic",
    "params": {}
  }
}

=== snapshot-labs/snapshot.js/test/examples/space-starknet-network.json
{
  "name": "Loot Owners",
  "skin": "indexed",
  "about": "",
  "admins": [
    "0xF296178d553C8Ec21A2fBD2c5dDa8CA9ac905A00"
  ],
  "avatar": "https://pbs.twimg.com/profile_images/1431587138202701826/lpgblc4h_400x400.jpg",
  "github": "lootproject",
  "symbol": "LOOT",
  "filters": {
    "minScore": 1,
    "onlyMembers": false
  },
  "members": [],
  "network": "0x534e5f4d41494e",
  "plugins": {},
  "twitter": "lootproject",
  "domain": "https://vote.lootproject.abc",
  "strategies": [
    {
      "name": "erc721",
      "params": {
        "symbol": "LOOT",
        "address": "0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7"
      }
    }
  ],
  "delegationPortal":{
    "delegationType": "compound-governor",
    "delegationContract": "0x05702362b68a350c1cae8f2a529d74fdbb502369ddcebfadac7e91da37636947",
    "delegationNetwork": "0x534e5f4d41494e",
    "delegationApi": "https://snapshot.org"
  },
  "validation": {
    "name": "basic",
    "params": {}
  },
  "voting": {
    "delay": 2592000,
    "period": 15552000,
    "quorum": 100
  }
}

=== snapshot-labs/snapshot.js/src/schemas/sample.json
{
  "name": "Sample",
  "network": "1",
  "symbol": "SAMPLE",
  "skin": "sample",
  "domain": "sample.com",
  "strategies": [
    {
      "name": "erc-20-balance-of",
      "params": {
        "address": "0x0AaCfbeC6a24756c20D41914F2caba817C0d8521",
        "symbol": "SAMPLE"
      }
    }
  ],
  "members": [
    "0x4C7909d6F029b3a5798143C843F4f8e5341a3473",
    "0x683A78bA1f6b25E29fbBC9Cd1BFA29A51520De84"
  ],
  "filters": {
    "defaultTab": "core",
    "minScore": 100,
    "onlyMembers": false,
    "invalids": [
      "Qmc4VSHwY3SVmo4oofhL2qDPaYcGaQqndM4oqdQQe2aZHQ",
      "QmTMAgnPy2q6LRMNwvj27PHvWEgZ3bw7yTtNNEucBZCWhZ"
    ]
  }
}
